language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js: "14"
git: 
  depth: 3
script:
  - yarn test
notifications: 
  slack: 
    secure: "VCyhtb0FYrkTN9bG+/YYQNXyWrMugFas8JpIwD4KGuvhL1svFrLT5KZhxWSXV+OUyWauhIzziSU4XEhQAr9O6V+89vDhThHNkPWTrOcUvu3S6HrnjWV9WMCYHpLl3IFWH/ytf2rWkorqCpvEEzs1odw5bz1f3A3E+CpsUC9grVd0oiyfQuVZBa8dmHW4RRmV/56HbO9+/UauHLj8O8GJmn4ONXdriUDeGO40Nhhj0rxdEPROm8BVmVGTqGQfWQvFv64J77YaDZdWXFD+6spZSWqkH8DD03lN6yoGX+kwH53mvyw9rBujambPKRm6sz/gUxfzGV57rRVombjoentAaAJfZ/fsaWNbWPo03luf8cWY2jvmLphl9dWFo/D7fEzJdanHPe1t4KQknAW/iBZEVyUUBIRCgrKSy28fPy6Df1kPPRKo9WdE9oWBQ5KyBIXtR2UkuSZ/wxBGv998MncRM4Vx+J2WgBmeOxIMAzcUEEklj8lDEFVGrj0wkUU50s2Y8IIwii0IxbVVnRM5tZcAViNwaMty7xTobj3UFYT9gOWZm83kcU/6Vz/+juCiSRvjkiffc8SW7isvg+qt5WCjXrJv5B9/zxKKOeBsgmBUqtdIIpSnr12wFOIOHUivtFkMwXelrtv3z3aRAfHtWNz7fJWgeOEjguEEiEtcR8eizTs="
  # email:
  #   recipients:
  #     - kanasir@hotmail.com
  #   on_success: always
  #   on_failure: always
